version: 2
jobs:
    build:
        working_directory: ~/circleci-demo-python-django
        docker:
            - image: circleci/python:3.6.1

dependencies:
    override:
        - make requirements

test:
    override:
        - coverage run ./manage.py test
    post:
        - coverage html --directory $CIRCLE_ARTIFACTS
